### PR TITLE
Multi-Gesture touchpad support

### PR DESCRIPTION
**Pull request by Nemec163**

### CODE REVIEW

**Comment by Nemec163** [comment]
Hi! I've added multi-gesture touchpad support instruction to README file

**Comment by Nemec163** [comment]
Also recommend to put files in to /Library/Extensions

**Comment by erikbdev** [comment]
I haven't decided to merge this request since currently VoodooI2C performs better than VoodooInput, but VoodooI2C does crash when loading with VoodooPS2.

**Comment by jryhonor** [comment]
I tried this in 10.15.3, only basic touchpad support.

**Comment by erikbdev** [comment]
> I tried this in 10.15.3, only basic touchpad support.

I will update on a guide on how to add multitouch support using VoodooI2C and VoodooPS2

**Pull request closed without merging**
